[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "GasketRAG"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
linux = "4.8"

[tasks]
postinstall="pip install flash-attn --no-build-isolation"

[dependencies]
python = "3.10.*"
faiss-gpu = ">=1.8.0,<2"
git-lfs = ">=3.5.1,<4"
cuda-nvcc = ">=12.6.68,<13"

[pypi-dependencies]
numpy = "==1.26.4"
torch = ">=2.4.0, <3"
transformers = ">=4.44.2, <5"
spacy = ">=3.7.6, <4"
flask = ">=3.0.3, <4"
ruamel-yaml = ">=0.18.6, <0.19"
colbert-ai = ">=0.2.21, <0.3"
pip = ">=24.2, <25"
accelerate = ">=0.34.2, <0.35"
trl = ">=0.10.1, <0.11"
datasets = "==2.*"
peft = ">=0.12.0, <0.13"
ipython = ">=8.27.0, <9"
openai = ">=1.45.0, <2"
jsonlines = ">=4.0.0, <5"
vllm = ">=0.6.1.post2, <0.7"


